#!/usr/bin/env bash
# installs nginx on webserver
# changes default webpage to print "Hello World!"
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
